### ISSUE TITLE
[First Try] Git Windows blog

### ISSUE THREAD

**Issue by gebilxs** [SEU-Master/seu.github.io#2]
![image](https://github.com/user-attachments/assets/3e09c502-16b3-4fb8-afdf-50f34812f506)
任务内容：提交git指南-windows流程 -> Blog模块
参考链接：https://blog.csdn.net/mukes/article/details/115693833
参与人员：2人

**Comment by baluit** [comment]
assign to me

**Comment by kailkako** [comment]
assign to me

**Comment by snow-like-kk** [comment]
assign to me

**Comment by ishuangdigan** [comment]
assign to me
