### ISSUE TITLE
[First Try] 更新README.md 和README_zh.md

### ISSUE THREAD

**Issue by gebilxs** [SEU-Master/seu.github.io#5]
告诉别人这个项目是S3DI知识库项目，参考其他优秀的开源项目的README.md 做第一步更新
参考链接：llama-factory,sealos的README
参与人数：2

**Comment by zhiyihy** [comment]
assign to me

**Comment by zelo789** [comment]
assign to me

**Comment by lichengyu52** [comment]
assign to me
